### ISSUE TITLE
[stacks] File content not displayed for stack deploy on Firefox 

### ISSUE THREAD

**Issue by neha-viswanathan** [appcelerator/portal#22]
In a Firefox browser, after uploading the stack file, the content of the stack file does not appear in the text area below.
 
![screenshot from 2017-06-16 13-54-33](https://user-images.githubusercontent.com/12013126/27244437-5b1faedc-529b-11e7-8aec-9b4eee4ae7fe.png)

**Comment by freignat91** [comment]
good catch!
